name: Build and Release Version

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MAVEN_OPTS: >-
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
          # cache: gradle

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: "./secrets"
          fileName: "my.keystore"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Decode and Replace `google-services.json`
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG | base64 --decode > google-services.json

      - name: Execute Gradle build
        env:
          STORE_FILE: ${{ github.workspace }}/secrets/my.keystore
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          SHIPBOOK_APP_ID: ${{ secrets.SHIPBOOK_APP_ID }}
          SHIPBOOK_APP_KEY: ${{ secrets.SHIPBOOK_APP_KEY }}
        run: |
          ./gradlew assembleRelease \
            -PSTORE_FILE="$STORE_FILE" \
            -PSTORE_PASSWORD="$STORE_PASSWORD" \
            -PKEY_ALIAS="$KEY_ALIAS" \
            -PKEY_PASSWORD="$KEY_PASSWORD"



      #   - name: Cache Gradle packages
      #     uses: actions/cache@v1
      #     with:
      #         path: ~/.gradle/caches
      #         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      #         restore-keys: ${{ runner.os }}-gradle

      - name: Verify APK Files
        run: find ${{ github.workspace }}/app/build/outputs/apk/ -name "*.apk"

      - name: Retrieve Version
        env:
          STORE_FILE: ${{ github.workspace }}/secrets/my.keystore
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          SHIPBOOK_APP_ID: ${{ secrets.SHIPBOOK_APP_ID }}
          SHIPBOOK_APP_KEY: ${{ secrets.SHIPBOOK_APP_KEY }}
        run: |
          ./gradlew -q printVersionName
          VERSION_NAME=$(./gradlew -q printVersionName)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        id: android_version


      - name: Rename APK
        run: mv ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/app/build/outputs/apk/release/notable-${{ env.VERSION_NAME }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/app/build/outputs/apk/release/notable-${{ env.VERSION_NAME }}.apk
          tag_name: v${{env.VERSION_NAME}}
          token: ${{ secrets.TOKEN }}
