name: Build and Release Version

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MAVEN_OPTS: >-
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
          # cache: gradle

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: "./secrets"
          fileName: "my.keystore"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Decode and Replace `google-services.json`
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG | base64 --decode > google-services.json

      - name: Execute Gradle build
        env:
          STORE_FILE: ${{ github.workspace }}/secrets/my.keystore
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          echo "Checking if keystore exists at $STORE_FILE..."
          if [ ! -f "$STORE_FILE" ]; then
            echo "ERROR: Keystore file not found at $STORE_FILE"
            exit 1
          fi
          ./gradlew assembleRelease \
            -PSTORE_FILE="$STORE_FILE" \
            -PSTORE_PASSWORD="$STORE_PASSWORD" \
            -PKEY_ALIAS="$KEY_ALIAS" \
            -PKEY_PASSWORD="$KEY_PASSWORD"



      #   - name: Cache Gradle packages
      #     uses: actions/cache@v1
      #     with:
      #         path: ~/.gradle/caches
      #         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      #         restore-keys: ${{ runner.os }}-gradle

      - name: Verify APK Files
        run: find ${{ github.workspace }}/app/build/outputs/apk/ -name "*.apk"

      - name: Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew \
           -PSTORE_FILE="../${{ steps.decode_keystore.outputs.filePath }}" \
           -PSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
           -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} \
           -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
          -q printVersionName)"
        id: android_version

      - name: Get version
        run: |
          echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

      - run: mv ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/app/build/outputs/apk/release/notable-${{ env.version_name }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/app/build/outputs/apk/release/notable-${{ env.version_name }}.apk
          tag_name: v${{env.version_name}}
          token: ${{ secrets.TOKEN }}
